version: '3'

services:

    # infrastructure
    infra-mysql:
        container_name: infra-mysql
        image: mysql
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - infrastructure:/var/lib/mysql
            - ./dumps:/docker-entrypoint-initdb.d
        networks: 
            - app
        environment:
            MYSQL_ROOT_PASSWORD: root

    ## mysql client
    ## https://hub.docker.com/_/mysql
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
          - 8080:8080

    ## application
    readus-backend:
        container_name: backend
        image: mukhtarharis/readus-backend:latest
        ports: 
            - 3000:3000
        restart: always
        depends_on: 
            - infra-mysql
        links: 
            - infra-mysql
        networks: 
            - app
        environment: 
            - MYSQL_HOSTNAME=infra-mysql
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=readus
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=root

    readus-frontend:
        container_name: frontend
        image: mukhtarharis/readus-frontend:latest
        ports: 
            - 8088:80
        restart: always
        depends_on: 
            - readus-backend
        networks: 
            - app
        links: 
            - readus-backend

volumes: 
    infrastructure: 
networks: 
    app: